name: upload visitor backend to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'backend/*'

env:
  PYTHON_VERSION: 3.11

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION }}

      - name: display python version
        run: python -c "import sys; print(sys.version)"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov moto boto3

      - name: run pytest with coverage report
        run: |
          pytest -vvv --capture=tee-sys --cov="/backend"